global_horizon/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

from newspapers_tracker.views import SingUpView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspapers_tracker.urls", namespace="newspapers_tracker")),
    path("registration/", include("django.contrib.auth.urls")),
    path("register/", SingUpView.as_view(), name="register")
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()

newspapers_tracker/urls.py
from django.urls import path

from newspapers_tracker.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDetailView,
    RedactorDeleteView,
    NewspaperList,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDetailView,
    NewspaperDeleteView,
    UserPasswordChangeView
)

app_name = "newspapers_tracker"

urlpatterns = [
    # Topic routes
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/update/<int:pk>/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/delete/<int:pk>/", TopicDeleteView.as_view(), name="topic-delete"),
    # Redactor routes
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors/update/<int:pk>/", RedactorUpdateView.as_view(), name="redactor-update"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/delete/<int:pk>/", RedactorDeleteView.as_view(), name="redactor-delete"),
    path("user/change_password/<int:pk>/", UserPasswordChangeView.as_view(), name="change-password"),
    # Newspaper routes
    path("newspapers/", NewspaperList.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/update/<int:pk>/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/delete/<int:pk>/", NewspaperDeleteView.as_view(), name="newspaper-delete"),

]

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
      <div class="container">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-12 col-md-6 my-auto">
            <div class="copyright text-center text-sm text-white text-lg-start">
              &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold text-white" target="_blank">Creative Tim</a>
              coded by AppSeed.
            </div>
          </div>
          <div class="col-12 col-md-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://github.com/app-generator/django-material-kit" class="nav-link text-white" target="_blank">Sources</a>
              </li>
              <li class="nav-item">
                <a href="https://appseed.us/support" class="nav-link text-white" target="_blank">Support</a>
              </li>
              <li class="nav-item">
                <a href="https://appseed.us" class="nav-link text-white" target="_blank">AppSeed</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer-components.html
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Company
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            About Us
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Team
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Products
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Blog
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Pricing
          </a>
        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-dribbble"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-twitter"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-instagram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-pinterest"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold" target="_blank">Creative Tim</a>
              coded by AppSeed.
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center mx-auto gap-5">
      <div class="col-md-2 mb-4">
        <div>
          <h6 class="font-weight-bolder mb-4">Pet project of<br>Vladimir Titarenko</h6>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-sm">Social Networks</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="https://www.instagram.com/flameh1story/" target="_blank">
                Instagram
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/T-Vlad-96" target="_blank">
                GitHub
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-sm">Contacts</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <span class="nav-link">tytarenkova@gmail.com</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
        class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip"
             title="Designed and Coded by Creative Tim" data-placement="bottom">
            <div class="w-10">
              <img
                src="{{ ASSETS_ROOT }}/img/istockphoto-929047972-612x612.jpg"
                alt="global horizon logo"
                class="img-fluid rounded-3 shadow-dark"
              >
            </div>
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 pe-5 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                  Pages
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a
                      href="{% url 'newspapers_tracker:topic-list' %}"
                      class="dropdown-item border-radius-md"
                    >
                      <span>Topics</span>
                    </a>
                    <a
                      href="{% url 'newspapers_tracker:redactor-list' %}"
                      class="dropdown-item border-radius-md"
                    >
                      <span>Redactors</span>
                    </a>
                    <a
                      href="{% url 'newspapers_tracker:newspaper-list' %}"
                      class="dropdown-item border-radius-md"
                    >
                      <span>Newspapers</span>
                    </a>
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                      Account
                    </h6>
                    <a
                      href="{% url 'login' %}"
                      class="dropdown-item border-radius-md"
                    >
                      <span>Sign In</span>
                    </a>
                  </div>
                  <div class="d-lg-none">
                    <a
                      href="{% url 'newspapers_tracker:topic-list' %}"
                      class="dropdown-item border-radius-md"
                    >
                      <span>Topics</span>
                    </a>
                    <a
                      href="{% url 'newspapers_tracker:redactor-list' %}"
                      class="dropdown-item border-radius-md"
                    >
                      <span>Redactors</span>
                    </a>
                    <a
                      href="{% url 'newspapers_tracker:newspaper-list' %}"
                      class="dropdown-item border-radius-md"
                    >
                      <span>Newspapers</span>
                    </a>
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                      Account
                    </h6>
                    <a href="/sign-in.html" class="dropdown-item border-radius-md">
                      <span>Sign In</span>
                    </a>
                  </div>
                </div>
              </li>

              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto d-flex">
                  <a
                    href="{% url 'newspapers_tracker:redactor-detail' pk=user.id %}"
                    class="nav-link nav-link-icon me-2"
                  >
                    User: {{ user }}
                  </a>
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="Sign OUT">
                      Logout
                    </p>
                  </a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}

<nav>
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform page=page_obj.previous_page_number %}">
          Prev
        </a>
      </li>
    {% endif %}

    <li class="page-item"><span class="page-link">{{ page_obj.number }}</span></li>

    {% if page_obj.number|add:"1" <= page_obj.paginator.num_pages %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform page=page_obj.number|add:"1" %}">
          {{ page_obj.number|add:"1" }}
        </a>
      </li>
    {% endif %}

    {% if page_obj.number|add:"2" <= page_obj.paginator.num_pages %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform page=page_obj.number|add:"2" %}">
          {{ page_obj.number|add:"2" }}
        </a>
      </li>
    {% endif %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform page=page_obj.next_page_number %}">
          Next
        </a>
      </li>
    {% endif %}

  </ul>
</nav>

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>