global_horizon/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

from newspapers_tracker.views import SingUpView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspapers_tracker.urls", namespace="newspapers_tracker")),
    path("registration/", include("django.contrib.auth.urls")),
    path("register/", SingUpView.as_view(), name="register")
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()

newspapers_tracker/urls.py
from django.urls import path

from newspapers_tracker.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDetailView,
    RedactorDeleteView,
    NewspaperList,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDetailView,
    NewspaperDeleteView,
    UserPasswordChangeView
)

app_name = "newspapers_tracker"

urlpatterns = [
    # Topic routes
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/update/<int:pk>/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/delete/<int:pk>/", TopicDeleteView.as_view(), name="topic-delete"),
    # Redactor routes
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors/update/<int:pk>/", RedactorUpdateView.as_view(), name="redactor-update"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/delete/<int:pk>/", RedactorDeleteView.as_view(), name="redactor-delete"),
    path("user/change_password/<int:pk>/", UserPasswordChangeView.as_view(), name="change-password"),
    # Newspaper routes
    path("newspapers/", NewspaperList.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/update/<int:pk>/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/delete/<int:pk>/", NewspaperDeleteView.as_view(), name="newspaper-delete"),

]

newspapers_tracker/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)


class Redactor(AbstractUser):
    years_of_experience = models.PositiveIntegerField(
        validators=[
            MaxValueValidator(70),
        ],
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return f"redactors/{self.id}"

    class Meta:
        ordering = ("username",)



class Newspaper(models.Model):
    title = models.CharField(max_length=255, unique=True)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("title",)

newspapers_tracker/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView

from newspapers_tracker.forms import (
    TopicForm,
    RedactorUpdateForm,
    RedactorCreateForm,
    NewspaperForm,
    TopicSearchForm,
    RedactorSearchForm,
    NewspaperSearchForm,
    SingUpForm,
    UserPasswordChangeForm
)
from newspapers_tracker.models import Topic, Newspaper, Redactor


class SingUpView(generic.CreateView):
    form_class = SingUpForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("login")


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_topics = Topic.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_redactors = get_user_model().objects.count()
    context = {
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
        "num_redactors": num_redactors,
    }
    return render(request, "newspapers_tracker/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5
    search_form = TopicSearchForm

    def get_context_data(self, *, object_list=..., **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = self.search_form(self.request.GET)
        return context

    def get_queryset(self):
        self.queryset = super().get_queryset()
        search_form = self.search_form(self.request.GET)
        if search_form.is_valid():
            self.queryset = self.queryset.filter(
                name__icontains=search_form.cleaned_data["name"]
            )
        return self.queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    form_class = TopicForm
    success_url = reverse_lazy("newspapers_tracker:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    form_class = TopicForm
    success_url = reverse_lazy("newspapers_tracker:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    template_name = "newspapers_tracker/topic_confirm_delete.html"
    success_url = reverse_lazy("newspapers_tracker:topic-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5
    search_form = RedactorSearchForm

    def get_context_data(self, *, object_list=..., **kwargs):
        context = super().get_context_data()
        context["search_form"] = self.search_form(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        search_form = self.search_form(self.request.GET)
        if search_form.is_valid():
            queryset = queryset.filter(
                username__icontains=search_form.cleaned_data.get("username")
            )
        return queryset


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreateForm
    success_url = reverse_lazy("newspapers_tracker:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspapers_tracker:redactor-list")


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    model = get_user_model()
    form_class = UserPasswordChangeForm
    template_name = "newspapers_tracker/user_password_change.html"

    def get_success_url(self):
        url = reverse_lazy(
            "newspapers_tracker:redactor-detail", kwargs={"pk": self.request.user.id}
        )
        return url

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Your password has successfully changed!✅")
        return response


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy(
        "newspapers_tracker:redactor-list"
    )
    template_name = "newspapers_tracker/redactor_confirm_delete.html"


class NewspaperList(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    search_form = NewspaperSearchForm

    def get_context_data(self, *, object_list=..., **kwargs):
        context = super().get_context_data()
        context["search_form"] = self.search_form(self.request.GET)
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        search_form = self.search_form(self.request.GET)
        if search_form.is_valid():
            queryset = queryset.filter(
                title__icontains=search_form.cleaned_data.get("title")
            )
        return queryset


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy(
        "newspapers_tracker:newspaper-list"
    )


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy(
        "newspapers_tracker:newspaper-list"
    )


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    template_name = "newspapers_tracker/newspaper_delete_confirm.html"
    success_url = reverse_lazy("newspapers_tracker:newspaper-list")

templates/newspapers_tracker/index.html
{% extends "layouts/base.html" %}
<body class="presentation-page bg-gray-200">

<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
  {% block content %}
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_topics }}">0</span>+</h1>
                  <h5 class="mt-3">Topics</h5>
                  <p class="text-sm font-weight-normal">...</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state2" countTo="{{ num_redactors }}">0</span>+</h1>
                  <h5 class="mt-3">Redactors</h5>
                  <p class="text-sm font-weight-normal">...</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_newspapers }}">0</h1>
                  <h5 class="mt-3">Newspapers</h5>
                  <p class="text-sm font-weight-normal">...</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  {% endblock content %}
</div>

{% block javascripts %}
  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
      if (document.getElementById('state1')) {
          const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
          if (!countUp.error) {
              countUp.start();
          } else {
              console.error(countUp.error);
          }
      }
      if (document.getElementById('state2')) {
          const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
          if (!countUp1.error) {
              countUp1.start();
          } else {
              console.error(countUp1.error);
          }
      }
      if (document.getElementById('state3')) {
          const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
          if (!countUp2.error) {
              countUp2.start();
          } else {
              console.error(countUp2.error);
          }
          ;
      }
  </script>
{% endblock javascripts %}
</body>

templates/newspapers_tracker/newspaper_delete_confirm.html
{% extends "layouts/base.html" %}

{% block content %}
  <div class="content">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="card">
          <div class="card-body text-center">
            <form action="" method="post">
              {% csrf_token %}
              <p>
                Are you sure you want to delete the
                <span class="fw-bold">{{ newspaper.title }}</span>?
              </p>
              <input
                type="submit"
                value="Delete"
                class="btn btn-sm btn-danger"
              >
              <input
                type="button"
                value="Cancel"
                class="btn btn-sm btn-secondary"
                onclick="javascript:history.back()"
              >
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/newspapers_tracker/newspaper_detail.html
{% extends "layouts/base.html" %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="card">
          <div class="card-body">
            <div class="row justify-content-end">
              <div class="col-sm-1">
                <a
                  href="{% url 'newspapers_tracker:newspaper-update' pk=newspaper.id %}"
                  class="btn-link fs-3"
                >
                  🖊
                </a>
              </div>
              <div class="col-sm-1">
                <a
                  href="{% url 'newspapers_tracker:newspaper-delete' pk=newspaper.id %}"
                  class="btn-link fs-3"
                >
                  🗑
                </a>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-md-8 mx-auto text-center">
                <h1 class="text-primary text-gradient">{{ newspaper.title }}</h1>
              </div>
            </div>
            <div class="row justify-content-start">
              <div class="col-lg-8 mx-auto">
                <ul class="list-group-flush">
                  <li class="list-group-item">
                    <span class="fw-bold">Topic: </span>
                    <span>{{ newspaper.topic.name }}</span>
                  </li>
                  <li class="list-group-item">
                    <span class="fw-bold">Published by: </span>
                    {% for publisher in newspaper.publishers.all %}
                      <span>{{ publisher }}, </span>
                    {% endfor %}
                  </li>
                  <li class="list-group-item">
                    <span class="fw-bold">
                      Published:
                    </span>
                    <span>{{ newspaper.published_date }}</span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-10 mx-auto">
                <div class="content-format p-3 rounded bg-light">
                  {{ newspaper.content|linebreaks }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/newspapers_tracker/newspaper_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <h1 class="text-center">
                  {{ object|yesno:"Update,Create" }}
                  Newspaper
                </h1>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                {% crispy form %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/newspapers_tracker/newspaper_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto mt-3">
        <div class="card">
          <div class="card-body text-dark text-center">
            <h1 class="text-gradient text-primary">
              Newspapers List
              <a
                href="{% url 'newspapers_tracker:newspaper-create' %}"
                class="float-end"
                title="Add newspaper"
              >
                +
              </a>
            </h1>
            <div>{% crispy search_form %}</div>
            <ul class="list-group">
              {% for newspaper in newspaper_list %}
                <li class="list-group-item d-flex justify-content-between border-0">
                  <div class="d-flex justify-content-center">
                    <span class="badge badge-circle bg-gradient bg-primary me-3">
                      {{ forloop.counter }}
                    </span>
                    <div>
                      <a href="{% url 'newspapers_tracker:newspaper-detail' pk=newspaper.id %}">
                        {{ newspaper }}
                      </a>
                    </div>
                  </div>
                  <div>
                    {{ newspaper.published_date }}
                  </div>
                </li>
              {% endfor %}
            </ul>
            <div class="d-flex justify-content-center mt-3">
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/newspapers_tracker/redactor_confirm_delete.html
{% extends "layouts/base.html" %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="card mt-3">
          <div class="card_body text-center">
            <form action="" method="post" class="text-dark">
              {% csrf_token %}
              <p class="fw-bold">
                Are you sure you want to delete
                <span class="text-primary text-gradient">
                  {{ redactor }}
                </span>
                ?
              </p>
              <input
                type="submit"
                value="Delete"
                class="btn btn-sm btn-danger btn-gradient"
              >
              <button
                type="button"
                value="Cancel"
                class="btn btn-sm btn-secondary bg-gradient"
                onclick="history.back()"
              >
                Cancel
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/newspapers_tracker/redactor_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="card">
          <div class="card-body text-center">
            <div class="row">
              <div class="col-sm-12 d-flex justify-content-end">
                {% if request.user.username == redactor.username %}
                  <a
                    href="{% url 'newspapers_tracker:change-password' redactor.id %}"
                    title="Change password"
                    class="btn-link fs-3 float-end mx-3"
                  >
                    🔓
                  </a>
                {% endif %}
                <a
                  href="{% url 'newspapers_tracker:redactor-delete' pk=redactor.id %}"
                  title="Delete Redactor"
                  class="btn-link fs-3 float-end mx-3"
                >
                  🗑
                </a>
                <a
                  href="{% url 'newspapers_tracker:redactor-update' pk=redactor.id %}"
                  title="Update Info"
                  class="btn-link fs-3 float-end"
                >
                  🖊
                </a>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12">
                <h1 class="text-primary">
                  {{ redactor }}
                  <span class="text-dark">Profile</span>
                </h1>
              </div>
            </div>
            <hr>
            <div class="row mb-3">

              <div class="col-md-6">
                <img src="" alt="Profile picture">
              </div>

              <div class="col-md-6">
                <ul class="list-group text-start">
                  <li class="list-group-item">
                    First Name: <span class="fw-bold">{{ redactor.first_name }}</span>
                  </li>
                  <li class="list-group-item">
                    Last Name: <span class="fw-bold">{{ redactor.last_name }}</span>
                  </li>
                  <li class="list-group-item">Email: <span class="fw-bold">{% if redactor.email %}
                    {{ redactor.email }} {% else %}<i>Email was not provided</i>{% endif %}</span>
                  </li>
                  <li class="list-group-item">
                    Experience: <span class="fw-bold">{{ redactor.years_of_experience }} years</span>
                  </li>
                </ul>
              </div>
            </div>
            <hr>
            <div class="row mt-3">
              <div class="col-12">
                <h2 class="text-center">{{ redactor }}'s newspapers</h2>
                <ul class="list-group border-0">
                  {% for newspaper in redactor.newspapers.all %}
                    <li class="list-group-item border-0 text-start mx-3">
                      <div class="row">
                        <div class="col-sm-1">
                        <span class="badge bg-primary bg-gradient me-1 rounded-circle">
                          #{{ forloop.counter }}
                        </span>
                        </div>
                        <div class="col-sm-3">
                          <a
                            href="{% url 'newspapers_tracker:newspaper-detail' newspaper.id %}"
                            class="fw-bold"
                          >
                            {{ newspaper }}
                          </a>
                        </div>
                        <div class="col-sm-8">
                        <span class="fw-bold mx-3">
                          published({{ newspaper.published_date }})
                       </span>
                        </div>
                      </div>
                    </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/newspapers_tracker/redactor_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}


{% block content %}
  <section class="pt-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg8">
          <div class="card">
            <div class="card-body text-center align-items-center">
              <h1 class="text-primary text-gradient">
                Redactor {{ object|yesno:"Update,Create" }}
              </h1>
              {% crispy form %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/newspapers_tracker/redactor_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
  <section class="pt-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="card">
            <div class="card-body text-center">
              <h1 class="text-primary text-gradient">
                Redactors List
                <a
                  href="{% url 'newspapers_tracker:redactor-create' %}"
                  class="float-end"
                  title="Add redactor"
                >
                  +
                </a>
              </h1>
              <div>{% crispy search_form %}</div>
              <div>
                <ul class="list-group list-group-flush">
                  {% for redactor in redactor_list %}
                    <li class="list-group-item d-flex justify-content-between py-3 px-4 border-0">
                      <a
                        href="{% url 'newspapers_tracker:redactor-detail' pk=redactor.id %}"
                        class="fw-bold"
                      >
                        {{ redactor.username }}
                      </a>
                      <div class="badge h-25 w-5 bg-primary bg-gradient rounded-circle">
                        #{{ forloop.counter }}
                      </div>
                    </li>
                  {% endfor %}
                </ul>
                <div class="d-flex justify-content-center mt-3">
                  {% include "includes/pagination.html" %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/newspapers_tracker/topic_confirm_delete.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <section class="pt-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <div class="card mt-3">
            <div class="card-body">
              <form action="" method="post" class="text-dark">
                {% csrf_token %}
                <p class="fw-bold">
                  Are you sure you want to delete
                  <span class="text-primary text-gradient">{{ topic.name }}</span>
                  ?
                </p>
                <input type="submit" value="delete" class="btn btn-danger bg-gradient">
                <button
                  type="button"
                  class="btn btn-secondary bg-gradient"
                  onclick="javascript:history.back()"
                >
                  Cancel
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/newspapers_tracker/topic_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <section class="pt-1 pb-4 mb-9">
    <div class="container py-3">
      <div class="row justify-content-center">
        <div class="card col-lg-8">
          <div class="card-body text-center">
            <h1 class="text-gradient text-primary">
              {{ object|yesno:'Update,Add' }} Topic
            </h1>
            {% crispy form %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/newspapers_tracker/topic_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <section class="pt-1 pb-4 mb-9">
    <div class="container py-3">
      <div class="row justify-content-center">
        <div class="card col-lg-8">
          <div class="card-body text-center">
            <div class="text-center">
              <h1 class="position-relative mb-4 text-primary">
                Topics
              </h1>
              <a
                href="{% url 'newspapers_tracker:topic-create' %}"
                class="position-absolute top-5 end-5 btn btn-primary bg-gradient fw-bold fs-6 rounded-pill"
                title="Add Topic"
              >
                +
              </a>
            </div>
            {% crispy search_form %}
            <ul class="list-group list-group-flush" id="topics_list">
              {% for topic in topic_list %}
                <li class="list-group-item d-flex justify-content-between py-3 px-4 border-0">
                  <a
                    href="{% url 'newspapers_tracker:topic-update' pk=topic.id %}"
                    class="fw-semibold"
                    title="Update Topic"
                  >
                    {{ topic.name }}
                  </a>
                  <a
                    href="{% url 'newspapers_tracker:topic-delete' pk=topic.id %}"
                    class="btn btn-sm bg-gray-100 rounded-circle"
                  >
                    🗑
                  </a>
                </li>
              {% endfor %}
            </ul>
            <div class="d-flex justify-content-center mt-3">
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/newspapers_tracker/user_password_change.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
  <section class="pt-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg8">
          <div class="card">
            <div class="card-body text-center align-items-center">
              <h1 class="text-primary text-gradient">
                {{ request.user }}'s password change
              </h1>
              {% crispy form %}
              <ul class="w-50 bg-gray-100 mx-auto text-start">
                <li><span>Your password can’t be too similar to your other personal information.</span></li>
                <li><span>Your password must contain at least 8 characters.</span></li>
                <li><span>Your password can’t be a commonly used password.</span></li>
                <li><span>Your password can’t be entirely numeric.</span></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}